// file: lib/baropts.js
//
// This code was automatically generated from:
// Barcode Writer in Pure PostScript - Version 2013-01-17-1
//
// Copyright (c) 2011-2013 Mark Warren
// Copyright (c) 2004-2012 Terry Burton
//
// See the COPYRIGHT file in the bwip.js root directory
// for the extended copyright notice.
var baropts = {
	"ean5":{
		includetext:false,
		height:0.7,
	},
	"ean2":{
		includetext:false,
		height:0.7,
	},
	"ean13":{
		includetext:false,
		height:1,
		addongap:12,
	},
	"ean8":{
		includetext:false,
		height:1,
		addongap:12,
	},
	"upca":{
		includetext:false,
		height:1,
		addongap:12,
	},
	"upce":{
		includetext:false,
		height:1,
		addongap:12,
	},
	"isbn":{
		includetext:false,
		height:1,
		addongap:12,
		legacy:false,
	},
	"ismn":{
		includetext:false,
		height:1,
		addongap:12,
		legacy:false,
	},
	"issn":{
		includetext:false,
		height:1,
		addongap:12,
	},
	"code128":{
		includetext:false,
		height:1,
		encoding:"auto",
		raw:false,
		parse:false,
		parsefnc:false,
	},
	"gs1-128":{
		includetext:false,
		height:0.5,
		linkagea:false,
		linkagec:false,
	},
	"ean14":{
		includetext:false,
		height:1,
	},
	"sscc18":{
		includetext:false,
		height:1,
	},
	"code39":{
		includecheck:false,
		includetext:false,
		includecheckintext:false,
		hidestars:false,
		height:1,
	},
	"code39ext":{
		includetext:false,
		parse:false,
	},
	"code32":{
		includetext:false,
		height:1,
	},
	"pzn":{
		includetext:false,
		height:1,
		pzn8:false,
	},
	"code93":{
		includecheck:false,
		includetext:false,
		height:1,
		parsefnc:false,
	},
	"code93ext":{
		includetext:false,
		parse:false,
	},
	"interleaved2of5":{
		includecheck:false,
		includetext:false,
		includecheckintext:false,
		height:1,
	},
	"itf14":{
		includetext:false,
		height:1,
	},
	"identcode":{
		includetext:false,
		height:1,
	},
	"leitcode":{
		includetext:false,
		height:1,
	},
	"databaromni":{
		height:33,
		linkage:false,
		format:"omni",
	},
	"databarstacked":{
	},
	"databarstackedomni":{
	},
	"databartruncated":{
	},
	"databarlimited":{
		height:10,
		linkage:false,
	},
	"databarexpanded":{
		height:34,
		format:"expanded",
		segments:-1,
		linkage:false,
	},
	"databarexpandedstacked":{
	},
	"pharmacode":{
		height:8,
		nwidth:0.5,
		wwidth:1.5,
		swidth:1.0,
	},
	"pharmacode2":{
		includetext:false,
		height:4,
	},
	"code2of5":{
		includecheck:false,
		includetext:false,
		includecheckintext:false,
		height:1,
		version:"industrial",
	},
	"code11":{
		includecheck:false,
		includetext:false,
		includecheckintext:false,
		height:1,
	},
	"bc412":{
		includecheck:false,
		includetext:false,
		includecheckintext:false,
		includestartstop:false,
		semi:false,
		height:1,
	},
	"rationalizedCodabar":{
		includecheck:false,
		includetext:false,
		includecheckintext:false,
		height:1,
	},
	"onecode":{
		height:0.15,
	},
	"postnet":{
		includetext:false,
		includecheckintext:false,
		height:0.125,
	},
	"planet":{
		includetext:false,
		includecheckintext:false,
		height:0.125,
	},
	"royalmail":{
		includetext:false,
		includecheckintext:false,
		height:0.175,
	},
	"auspost":{
		includetext:false,
		height:0.175,
		custinfoenc:"character",
	},
	"kix":{
		includetext:false,
		includecheckintext:false,
		height:0.175,
	},
	"japanpost":{
		includetext:false,
		includecheckintext:false,
		height:0.175,
	},
	"msi":{
		includecheck:false,
		includetext:false,
		includecheckintext:false,
		checktype:"mod10",
		badmod11:false,
		height:1,
	},
	"plessey":{
		includetext:false,
		includecheckintext:false,
		unidirectional:false,
		height:1,
	},
	"telepen":{
		numeric:false,
		includetext:false,
		height:1,
		parse:false,
	},
	"posicode":{
		includetext:false,
		height:1,
		encoding:"auto",
		version:"a",
		checkoffset:0,
		raw:false,
		parse:false,
		parsefnc:false,
	},
	"codablockf":{
		rows:-1,
		columns:8,
		rowheight:10,
		sepheight:1,
		encoding:"auto",
		parse:false,
		parsefnc:false,
	},
	"code16k":{
		mode:-1,
		pos:-1,
		rows:0,
		rowheight:8,
		sepheight:1,
		encoding:"auto",
		raw:false,
		parse:false,
		parsefnc:false,
	},
	"code49":{
		mode:-1,
		pos:-1,
		rows:0,
		rowheight:8,
		sepheight:1,
		parse:false,
		parsefnc:false,
	},
	"channelcode":{
		shortfinder:false,
		includetext:false,
		includecheck:false,
		height:1,
	},
	"flattermarken":{
		includetext:false,
		height:0.3,
	},
	"raw":{
		height:1,
	},
	"daft":{
		height:0.175,
	},
	"symbol":{
	},
	"pdf417":{
		compact:false,
		eclevel:-1,
		columns:0,
		rows:0,
		rowmult:3,
		ccc:false,
		raw:false,
		parse:false,
	},
	"micropdf417":{
		columns:0,
		rows:0,
		rowmult:2,
		cca:false,
		ccb:false,
		raw:false,
		parse:false,
	},
	"datamatrix":{
		columns:0,
		rows:0,
		encoding:"ascii",
		raw:false,
		parse:false,
		parsefnc:false,
	},
	"qrcode":{
		format:"full",
		version:"unset",
		eclevel:"unset",
		encoding:"unset",
		raw:false,
		parse:false,
	},
	"maxicode":{
		mode:-1,
		sam:-1,
		parse:false,
	},
	"azteccode":{
		format:"unset",
		readerinit:false,
		layers:-1,
		eclevel:23,
		ecaddchars:3,
		raw:false,
		parse:false,
	},
	"codeone":{
		version:"unset",
		encoding:"ascii",
		raw:false,
		parse:false,
	},
	"gs1-cc":{
		ccversion:"a",
		cccolumns:-1,
		lintype:"",
		linwidth:-1,
	},
	"ean13composite":{
	},
	"ean8composite":{
	},
	"upcacomposite":{
	},
	"upcecomposite":{
	},
	"databaromnicomposite":{
	},
	"databarstackedcomposite":{
	},
	"databarstackedomnicomposite":{
	},
	"databartruncatedcomposite":{
	},
	"databarlimitedcomposite":{
	},
	"databarexpandedcomposite":{
	},
	"databarexpandedstackedcomposite":{
	},
	"gs1-128composite":{
	},
	"gs1datamatrix":{
	},
	"hibccode39":{
	},
	"hibccode128":{
	},
	"hibcdatamatrix":{
	},
	"hibcpdf417":{
		columns:2,
	},
	"hibcmicropdf417":{
		columns:2,
	},
	"hibcqrcode":{
	},
	"hibccodablockf":{
	},
};
